//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSApp.CMSResources.Demo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMSApp.CMSResources.Demo.default", typeof(_default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string ObjectType_demo_bar {
            get {
                return ResourceManager.GetString("ObjectType.demo_bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baz.
        /// </summary>
        internal static string ObjectType_demo_baz {
            get {
                return ResourceManager.GetString("ObjectType.demo_baz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo.
        /// </summary>
        internal static string ObjectType_demo_foo {
            get {
                return ResourceManager.GetString("ObjectType.demo_foo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo Bars.
        /// </summary>
        internal static string ObjectType_demo_foobar {
            get {
                return ResourceManager.GetString("ObjectType.demo_foobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo Bazs.
        /// </summary>
        internal static string ObjectType_demo_foobaz {
            get {
                return ResourceManager.GetString("ObjectType.demo_foobaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo Categories.
        /// </summary>
        internal static string ObjectType_demo_foocategory {
            get {
                return ResourceManager.GetString("ObjectType.demo_foocategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Bazs.
        /// </summary>
        internal static string ObjectType_demo_nodebaz {
            get {
                return ResourceManager.GetString("ObjectType.demo_nodebaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Foos.
        /// </summary>
        internal static string ObjectType_demo_nodefoo {
            get {
                return ResourceManager.GetString("ObjectType.demo_nodefoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Region.
        /// </summary>
        internal static string ObjectType_demo_noderegion {
            get {
                return ResourceManager.GetString("ObjectType.demo_noderegion", resourceCulture);
            }
        }
    }
}
