//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Test;

[assembly: RegisterDocumentType(Banner.CLASS_NAME, typeof(Banner))]

namespace CMS.DocumentEngine.Types.Test
{
	/// <summary>
	/// Represents a content item of type Banner.
	/// </summary>
	public partial class Banner : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Test.Banner";


		/// <summary>
		/// The instance of the class that provides extended API for working with Banner fields.
		/// </summary>
		private readonly BannerFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BannerID.
		/// </summary>
		[DatabaseIDField]
		public int BannerID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BannerID"), 0);
			}
			set
			{
				SetValue("BannerID", value);
			}
		}


		/// <summary>
		/// Banner Name.
		/// </summary>
		[DatabaseField]
		public string BannerName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BannerName"), @"");
			}
			set
			{
				SetValue("BannerName", value);
			}
		}


		/// <summary>
		/// Image Url.
		/// </summary>
		[DatabaseField]
		public string BannerImageUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BannerImageUrl"), @"");
			}
			set
			{
				SetValue("BannerImageUrl", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Banner fields.
		/// </summary>
		[RegisterProperty]
		public BannerFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Banner fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BannerFields : AbstractHierarchicalObject<BannerFields>
		{
			/// <summary>
			/// The content item of type Banner that is a target of the extended API.
			/// </summary>
			private readonly Banner mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BannerFields" /> class with the specified content item of type Banner.
			/// </summary>
			/// <param name="instance">The content item of type Banner that is a target of the extended API.</param>
			public BannerFields(Banner instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BannerID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BannerID;
				}
				set
				{
					mInstance.BannerID = value;
				}
			}


			/// <summary>
			/// Banner Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.BannerName;
				}
				set
				{
					mInstance.BannerName = value;
				}
			}


			/// <summary>
			/// Image Url.
			/// </summary>
			public string ImageUrl
			{
				get
				{
					return mInstance.BannerImageUrl;
				}
				set
				{
					mInstance.BannerImageUrl = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Banner" /> class.
		/// </summary>
		public Banner() : base(CLASS_NAME)
		{
			mFields = new BannerFields(this);
		}

		#endregion
	}
}