//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Test;

[assembly: RegisterDocumentType(Testing.CLASS_NAME, typeof(Testing))]

namespace CMS.DocumentEngine.Types.Test
{
	/// <summary>
	/// Represents a content item of type Testing.
	/// </summary>
	public partial class Testing : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Test.Testing";


		/// <summary>
		/// The instance of the class that provides extended API for working with Testing fields.
		/// </summary>
		private readonly TestingFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TestingID.
		/// </summary>
		[DatabaseIDField]
		public int TestingID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TestingID"), 0);
			}
			set
			{
				SetValue("TestingID", value);
			}
		}


		/// <summary>
		/// TestingName.
		/// </summary>
		[DatabaseField]
		public string TestingName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TestingName"), @"");
			}
			set
			{
				SetValue("TestingName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Testing fields.
		/// </summary>
		[RegisterProperty]
		public TestingFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Testing fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TestingFields : AbstractHierarchicalObject<TestingFields>
		{
			/// <summary>
			/// The content item of type Testing that is a target of the extended API.
			/// </summary>
			private readonly Testing mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TestingFields" /> class with the specified content item of type Testing.
			/// </summary>
			/// <param name="instance">The content item of type Testing that is a target of the extended API.</param>
			public TestingFields(Testing instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TestingID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TestingID;
				}
				set
				{
					mInstance.TestingID = value;
				}
			}


			/// <summary>
			/// TestingName.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.TestingName;
				}
				set
				{
					mInstance.TestingName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Testing" /> class.
		/// </summary>
		public Testing() : base(CLASS_NAME)
		{
			mFields = new TestingFields(this);
		}

		#endregion
	}
}